#include <stdio.h>

#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#include "libavfilter/avfilter.h"
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hh_myapplication_MainActivity */
#include <android/log.h>
#define LOGE(format, ...)  __android_log_print(ANDROID_LOG_ERROR, "(>_<)", format, ##__VA_ARGS__)

struct  URLProtocol;
/*
 * Class:     com_example_hh_myapplication_MainActivity
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hh_myapplication_MainActivity_urlprotocolinfo
        (JNIEnv *env, jobject obj){
    char info[40000]={0};
    av_register_all();
    struct URLProtocol *pup = NULL;
    //input
    struct URLProtocol **p_temp = &pup;
    avio_enum_protocols((void **)p_temp, 0);
    while ((*p_temp) != NULL){
             sprintf(info, "%s[In ][%10s]\n", info, avio_enum_protocols((void **)p_temp, 0));
     }
    pup = NULL;
    //Output
    avio_enum_protocols((void **)p_temp, 1);
    while ((*p_temp) != NULL){
        sprintf(info, "%s[Out][%10s]\n", info, avio_enum_protocols((void **)p_temp, 1));
    }
    //LOGE("%s", info);
     return (*env)->NewStringUTF(env, info);
}

/*
 * Class:     com_example_hh_myapplication_MainActivity
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hh_myapplication_MainActivity_avformatinfo
        (JNIEnv *env, jobject obj){

   return (*env)->NewStringUTF(env, "Hello from JNI !  Compiled with ABI4 .");

    //return env->NewStringUTF(env,"HELLOHLLO");
}

/*
 * Class:     com_example_hh_myapplication_MainActivity
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hh_myapplication_MainActivity_avcodecinfo
        (JNIEnv *env, jobject obj){
    return (*env)->NewStringUTF(env,"HELLOHLLO1");
}

/*
 * Class:     com_example_hh_myapplication_MainActivity
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hh_myapplication_MainActivity_avfilterinfo
        (JNIEnv *env, jobject obj){
    return (*env)->NewStringUTF(env,"HELLOHLLO2");
}

/*
 * Class:     com_example_hh_myapplication_MainActivity
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hh_myapplication_MainActivity_configurationinfo
        (JNIEnv *env, jobject obj){
    //std::string hello = "Hello from C++";
    //return (*env)->NewStringUTF(env,hello);
    return (*env)->NewStringUTF(env, "Hello from JNI !  Compiled with ABI3.");
}
